[package]
name = "huffman"
version = "0.1.0"
authors = ["Nicklas Sedlock <nicklas.sedlock@posteo.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
priority-queue = "1.1.0"
bit-vec = "0.6"
endio_bit = "0.2.0"
