[package]
name = "huffman"
version = "0.1.0"
authors = ["Nicklas Sedlock <nicklas.sedlock@posteo.net>"]
edition = "2018"

[dependencies]
priority-queue = "1.1.0"
bit-vec = "0.6"
endio_bit = "0.2.0"
termprogress = "0.3.4"
num-format = "0.4.0"
clap = "2.33.3"
